# Dependencies
markdown:         redcarpet
highlighter:      pygments
baseurl:          /xray

# Permalinks
permalink:        pretty

# Setup
title:            'XRay'
tagline:          'Transparency for the Web.'
description:      ''
url:              http://mathias.lecuyer.me

paginate:         1
paginate_path:    /xray/blog/page:num

# Custom vars
version:          0.1
