# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'XRay'
bio:              'Transparency for the Web.'
tagline:          ''
description:      ''
url:              http://mathias.lecuyer.me

author:
  name:           'Mathias Lecuyer'
  url:            https://twitter.com/matlecu

paginate:         1
paginate_path:    /xray/blog/page:num

# Custom vars
version:          0.1
